# Generated by Django 5.0.6 on 2024-06-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='profile_pics/')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
            ],
        ),
    ]
